#Robot Frames (CHECK URDF)
base_link: "base_link"
lfoot: "l_ankle"
rfoot: "r_ankle"
modelname: "/home/master/dp_ws/src/serow/share/urdf/nao.urdf"
#ROS Topic Names
usePoseUpdate: false  #if true specify camera_vo_topic otherwise use odom
pose_topic: "/orbslam2/pose" #only if usePoseUpdate is true
useLegOdom: true
odom_topic: "/vins_estimator/odometry" #only if usePoseUpdate is false and useLegOdom is false
#odom_topic: "/nao_robot/odom"
imu_topic: "/nao_robot/imu"
joint_state_topic: "/joint_states"
lfoot_force_torque_topic: "/nao_robot/LLeg/force_torque_states"
rfoot_force_torque_topic: "/nao_robot/RLeg/force_torque_states"
copl_topic: "/nao_robot/LLeg/COP"
copr_topic: "/nao_robot/RLeg/COP"

#Ground-Truth
ground_truth: false
ground_truth_odom_topic: " "
ground_truth_com_topic: " "


support_idx_provided: false
support_idx_topic: " "

#To publish relative data
debug_mode: true


#TF from IMU to Body 
#For imu0 (external IMU)
#T_B_I: [0, 0, 1, 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0 ,0, 1]
#For nao imu (onboard IMU)
T_B_A: [-1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,-1 ,0, 0, 0, 0 ,0, 1]
T_B_G: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 ,0, 1]
#TF from External Pose to Body only if useLegOdom is false
T_B_P: [0, 1, 0, 0, -1, 0, 0, 0, 0, 0 ,1 ,0, 0, 0, 0, 1]
#T_B_P: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 , 1]

#ROS Topic Frequencies in Hz
imu_topic_freq: 100
joint_topic_freq: 100
fsr_topic_freq: 100  

##Schmitt Trigger - Contact Classifier
LLegUpThres: 20 #Schmitt Trigger High Threshold in Newtons (N)
LLegLowThres: 12 #Schmitt Trigger Low Threshold in Newtons (N)
LosingContact: 7
StrikingContact: 60

#Steady State Joint Kalman Filter (KF)
estimateJoints: true #Use a Steady State KF in every joint
joint_cutoff_freq: 10

#Madgwick Filter for attitude
Madgwick_gain: 0.3


#Complimentary Filter for Body Velocity  //Used in Leg Odometry
useCF: false
freqvmin: 0.1
freqvmax: 2.5

#Rigid body Extended Kalman Filter (EKF)
#To estimate:
# 3-D Body Position/Velocity
# 3-D IMU-Biases

#Process Noise STDs
accelerometer_bias_random_walk:  0.03904 #m/s^2/sqrt(s)
gyroscope_bias_random_walk: 0.00283344 # rad/s/sqrt(s)
accelerometer_noise_density: 0.163 #m/s^2
gyroscope_noise_density: 0.09525 #rad/s



#Measuremets
#Odometry Measurement Noise std:
odom_position_noise_density: 1.0e-03
odom_orientation_noise_density: 1.0e-03

velocity_noise_density: 5.0e-03;


#IMU Initial Biases
#bias_ax:  -0.239618
#bias_ay: 0.0751756
#bias_az: -18.0327
#bias_gx:  -0.000817362
#bias_gy:  -0.00178242
#bias_gz:  0.000158554

bias_ax:  0.239618
bias_ay:  -0.1934
bias_az:   18.0327
bias_gx:  -0.000817362
bias_gy:  -0.00178242
bias_gz:  0.0




#Filter Params
gravity: 9.80665 #gravity constant (m/s^2)
medianWindow: 10

# CoM Extended Kalman Filter (EKF)
# To estimate:
# CoM 3-D Position/Velocity
# 3-D External Forces on the CoM
estimateCoM: true   #Use the CoM EKF

#---------------------------------------------#
#Specify the rest only if estimateCoM is true!!
#---------------------------------------------#


#Process Noise
com_position_random_walk: 1.0e-6 #in m
com_velocity_random_walk: 1.0e-2 #in m/s
external_force_random_walk: 0.5      #in Newtons
#Measurment Noise
com_position_noise_density: 1.0e-04  #CoM position in m
com_acceleration_noise_density: 5.0e-02 #CoM Acceleration in m/s^2
#Initial errors in External Forces
bias_fx: 0.0  #in Newtons
bias_fy: 0.0
bias_fz: 0.0
#Gyro LPF
useGyroLPF: false
#Cutt-off Frequencies
gyro_cut_off_freq: 10.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 10 #buffer size, the larger the smoother and delayed the signal, only if useGyroLPF is false
#Filter Params
mass: 5.182530  #robot mass
Ixx : 0.0050623407587  #torso inertia around x
Iyy : 0.0048801358789  #torso inetria around y
Izz : 0.001610300038   #torso inertia around z
