#Robot Frames (CHECK URDF)

base_link: "pelvis"
lfoot: "leftFoot"
rfoot: "rightFoot"
modelname: "/home/master/dp_ws/src/serow/share/urdf/valkyrie_sim.urdf"

useLegOdom: false

#ROS Topic Names


odom_topic: "/ihmc_ros/valkyrie/output/visual_odom" #only if usePoseUpdate is false and useLegOdom is false
usePoseUpdate: false  #if true specify pose_topic / Do not use if odom_topic is set
pose_topic: "" #only if usePoseUpdate is true

imu_topic: "/pelvisMiddleImu/imu"
joint_state_topic: "/ihmc_ros/valkyrie/output/joint_states"
lfoot_force_torque_topic: "/ihmc_ros/valkyrie/output/foot_force_sensor/left"
rfoot_force_torque_topic: "/ihmc_ros/valkyrie/output/foot_force_sensor/right"
copl_topic: "/ihmc_ros/valkyrie/output/cop/left"
copr_topic: "/ihmc_ros/valkyrie/output/cop/right"



#Choose Integration Method
#Euler Method for faster execution if false the Runge-Kutta 4 method will be used 
useEuler: true





#Ground-Truth
ground_truth: true
ground_truth_odom_topic: "/valkyrie/ground_truth/odom"
ground_truth_com_topic: "/valkyrie/ground_truth/CoM"

is_in_ds_topic: "/ihmc_ros/valkyrie/output/capturability/is_in_double_support"

support_idx_provided: false
support_idx_topic: "/ihmc_ros/valkyrie/output/support_idx"

#To publish relative data
debug_mode: true


#TF from IMU to Body
T_B_A: [1, 0, 0, 0, 0, -1, 0, 0, 0, 0 ,-1 ,-0.108, 0, 0 ,0, 1]
T_B_G: [1, 0, 0, 0, 0, -1, 0, 0, 0, 0 ,-1 ,-0.108, 0, 0 ,0, 1]

#TF from External Pose to Body only if useLegOdom is false
#T_B_P: [0, 1, 0, 0, -1, 0, 0, 0, 0, 0 ,1 ,0, 0, 0, 0, 1]
T_B_P: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 , 1]


#ROS Topic Frequencies in Hz
imu_topic_freq: 500
joint_topic_freq: 500
fsr_topic_freq: 500  

##Schmitt Trigger - Contact Classifier
LLegUpThres: 250 #Schmitt Trigger High Threshold in Newtons (N)
LLegLowThres: 80 #Schmitt Trigger Low Threshold in Newtons (N)
LosingContact: 20
StrikingContact: 1500

#Steady State Joint Kalman Filter (KF)
estimateJoints: true #Use a Steady State KF in every joint
joint_cutoff_freq: 18

#Madgwick Filter for attitude
Madgwick_gain: 0.012

#Complimentary Filter for Body Velocity  //Used in Leg Odometry
useCF: false
freqvmin: 0.1
freqvmax: 2.5




#Rigid body Extended Kalman Filter (EKF)
#To estimate:
# 3-D Body Position/Velocity
# 3-D IMU-Biases

#Process Noise STDs
accelerometer_bias_random_walk:  0.5 #m/s^2/sqrt(s)
gyroscope_bias_random_walk: 4.1884e-2 # rad/s/sqrt(s)
accelerometer_noise_density: 1.7 #m/s^2  #Continuous Time
gyroscope_noise_density: 0.2 #rad/s  #Continuous Time


#Measuremets
#Odometry Measurement Noise std:
odom_position_noise_density: 1.0e-2
odom_orientation_noise_density: 1.0e-2

velocity_noise_density: 1.0;


#IMU Initial Biases - Biases are substracted!
bias_ax: 0.0
bias_ay: 0.0
bias_az: 9.7997
bias_gx: -1.60298e-05
bias_gy: -1.24745e-05
bias_gz: -2.60968e-05



#Filter Params
gravity: 9.80 #gravity constant (m/s^2)
medianWindow: 11




# CoM Extended Kalman Filter (EKF)
# To estimate:
# CoM 3-D Position/Velocity
# 3-D External Forces on the CoM
estimateCoM: true   #Use the CoM EKF

#---------------------------------------------#
#Specify the rest only if estimateCoM is true!!
#---------------------------------------------#


#Process Noise
com_position_random_walk: 5.0e-1 #in m
com_velocity_random_walk: 1.0 #in m/s
external_force_random_walk: 100.0   #in Newtons
#Measurment Noise
com_position_noise_density: 1.0  #CoM position in m
com_acceleration_noise_density: 2.5 #CoM Acceleration in m/s^2
#Initial errors in External Forces
bias_fx: -23.5  #in Newtons
bias_fy: -24.0
bias_fz: -55.0
#Gyro LPF
useGyroLPF: false
#Cutt-off Frequencies
gyro_cut_off_freq: 10.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 15 #buffer size, the larger the smoother and delayed the signal, only if useGyroLPF is false
#Filter Params
mass: 127.324  #robot mass
Ixx : 0.11866378  #torso inertia around x
Iyy : 0.097963425  #torso inetria around y
Izz : 0.083854638   #torso inertia around z
