#Robot Frames (CHECK URDF)
base_link: "base_link"
lfoot: "l_ankle"
rfoot: "r_ankle"
modelname: "/home/master/ros_ws/src/serow/share/urdf/nao.urdf"

#ROS Topic Names

useLegOdom: false
#odom_topic: "/svo/odom/0"
odom_topic: "/odom_rf2o"
imu_topic: "/nao_robot/imu"
joint_state_topic: "/joint_states"
lfoot_force_torque_topic: "/nao_robot/LLeg/force_torque_states"
rfoot_force_torque_topic: "/nao_robot/RLeg/force_torque_states"


#Ground-Truth
ground_truth: false
ground_truth_odom_topic: "/nao/ground_truth/odom"
ground_truth_com_topic: "/gt_com"
T_B_GT: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0 ,0, 1]

comp_with: true
#comp_with_odom0_topic: "/svo/odom/0"
comp_with_odom0_topic: "/odom_rf2o"
support_idx_provided: false
support_idx_topic: "/sp"

#To publish relative data
debug_mode: true


#TF from IMU to Body 
#For nao imu (onboard IMU)
T_B_A: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 ,0, 1]
T_B_G: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 ,0, 1]
#TF from F/T to Left Foot
T_FT_LL: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1]
#TF from F/T to Right Foot
T_FT_RL: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1]
#TF from External Odom to Body only if useLegOdom is false
#T_B_P: [0, 1, 0, 0, -1, 0, 0, 0, 0, 0 ,1 ,0, 0, 0, 0, 1] #VINS
T_B_P: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 , 1] #rf2o
#T_B_P: [0, 0, 1, 0, -1, 0, 0, 0, 0, -1 ,0 ,0, 0, 0, 0, 1] #SVO without imu
#ROS Topic Frequencies in Hz
imu_topic_freq: 100
joint_topic_freq: 100
fsr_topic_freq: 100  

##Schmitt Trigger - Contact Classifier
LegUpThres: 20 #Schmitt Trigger High Threshold in Newtons (N)
LegLowThres: 12 #Schmitt Trigger Low Threshold in Newtons (N)
LosingContact: 7
StrikingContact: 60


#Joint Velocity Estimation
joint_cutoff_freq: 16.0
joint_noise_density: 0.5
#Mahony Filter for attitude
useMahony: true
Mahony_Kp: 0.9
Mahony_Ki: 0.0
#Madgwick Filter for attitude if useMahony is false
Madgwick_gain: 0.3


#Leg Odometry Coefficients
Tau0: 1.0
Tau1: 1.0
medianWindow: 8
#mass: 6.6530  #robot mass
mass: 5.6  #robot mass with realsense and IMU

#mass: 6.6530  #robot mass with RP-LIDAR

#Rigid body Extended Kalman Filter (EKF)
#To estimate:
# 3-D Body Position/Velocity
# 3-D IMU-Biases

#Process Noise STDs
accelerometer_bias_random_walk:  0.00499 #m/s^2
gyroscope_bias_random_walk: 0.00283344 # rad/s
accelerometer_noise_density: 0.0186 #m/s^2 
gyroscope_noise_density: 0.00968 #rad/s 


#VO Measuremets
#Odometry Measurement Noise std:
leg_odom_position_noise_density: 5.0e-04 #m
leg_odom_orientation_noise_density: 5.0e-02 #rad

useOutlierDetection: false
#mahalanobis_TH: 9
mahalanobis_TH: -1
#Odom Measurements
#odom_position_noise_density: 5.0e-02 #2.0e-01
#odom_orientation_noise_density: 5.0e-02 #2.0e-01

#RP Lidar Odom
odom_position_noise_density: 0.012 #m 
odom_orientation_noise_density: 5.0e-02 #rad

velocity_noise_density_x: 0.013 #m/s
velocity_noise_density_y: 0.013 #m/s
velocity_noise_density_z: 0.013 #m/s


#IMU Initial Biases - Biases are substracted!
bias_ax: 0.639618 #m/s^2
bias_ay: -0.1934  #m/s^2
#bias_ay: -0.0751756
bias_az:  0.0 #m/s^2
bias_gx: -0.000817362 #rad
bias_gy: -0.00178242  #rad
bias_gz: -0.000158554 #rad
calibrateIMUbiases: true #otherwise specify accurate initial values for bias_a, bias_g
maxImuCalibrationCycles: 2000



#Filter Params
gravity: 9.80 #gravity constant (m/s^2)


# CoM Extended Kalman Filter (EKF)
# To estimate:
# CoM 3-D Position/Velocity
# 3-D External Forces on the CoM
estimateCoM: true   #Use the CoM EKF

#---------------------------------------------#
#Specify the rest only if estimateCoM is true!!
#---------------------------------------------#


#Process Noise
com_position_random_walk: 1.0e-4 #in m
com_velocity_random_walk: 5.0e-3 #in m/s
external_force_random_walk: 1.0      #in Newtons
#Measurment Noise
com_position_noise_density: 1.0e-4  #CoM position in m
com_acceleration_noise_density: 2.5e-01 #CoM Acceleration in m/s^2
#Initial errors in External Forces
bias_fx: 0.678  #in Newtons
bias_fy: 0.5658
bias_fz: 0.94869
#Gyro LPF
useGyroLPF: false
#Cutt-off Frequencies
gyro_cut_off_freq: 10.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 14 #buffer size, the larger the smoother and delayed the signal, only if useGyroLPF is false
#Filter Params
Ixx : 0.0050623407587  #torso inertia around x
Iyy : 0.0048801358789  #torso inetria around y
Izz : 0.001610300038   #torso inertia around z
