#Robot Frames (CHECK URDF)

isQuadruped: true
base_link: "base"
LFfoot: "FL_foot"
RFfoot: "FR_foot"
LHfoot: "RL_foot"
RHfoot: "RR_foot"
modelname: "/home/master/catkin_ws/src/serow/share/urdf/go1.urdf"

useLegOdom: true
#ROS Topic Names
odom_topic: "/svo/odom0" #only if usePoseUpdate is false and useLegOdom is false
imu_topic: "/imu"
joint_state_topic: "/joint_states"

LFfoot_force_torque_topic: "/force_estimation/FL"
RFfoot_force_torque_topic: "/force_estimation/FR"
LHfoot_force_torque_topic: "/force_estimation/RL"
RHfoot_force_torque_topic: "/force_estimation/RR"

#Ground-Truth #Not Mandatory - For comparison only
ground_truth: false
ground_truth_odom_topic: ""
ground_truth_com_topic: ""
T_B_GT: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0 ,0, 1]

comp_with: false
comp_with_odom0_topic: ""

#To publish relative data
debug_mode: false

#TF from IMU to Body
T_B_A: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1, 0, 0, 0 ,0, 1]
T_B_G: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1, 0, 0, 0 ,0, 1]

#TF from F/T to Left Foot
T_FT_LF: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0, 0, 1]
T_FT_LH: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0, 0, 1]

#TF from F/T to Right Foot
T_FT_RF: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0, 0, 1]
T_FT_RH: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0, 0, 1]

#TF from External Pose to Body only if useLegOdom is false
T_B_P: [0, 0, 1, 0, -1, 0, 0, 0, 0, -1 ,0 ,0, 0, 0, 0, 1] #SVO without imu

#ROS Topic Frequencies in Hz
imu_topic_freq: 500
joint_topic_freq: 500
ft_topic_freq: 500

mass: 12.0  #robot mass

##Schmitt Trigger - Contact Classifier
LegUpThres: 190.0 #Schmitt Trigger High Threshold in Newtons (N)
LegLowThres: 135.0 #Schmitt Trigger Low Threshold in Newtons (N)
LosingContact: 50.0
StrikingContact: 240
medianWindow: 9

# Use the joint velocities in the ros joint states if available or numerically
# compute them from joint positions
computeJointVelocity: true
#Or Compute Joint Velocities/Only if computeJointVelocity is true
joint_cutoff_freq: 50

#Mahony Filter for attitude
useMahony: false
Mahony_Kp: 2.5
Mahony_Ki: 0.0
#Madgwick Filter for attitude if useMahony is false
Madgwick_gain: 0.01

#Leg Odometry Coefficients
Tau0: 1.0
Tau1: 0.0 #No F/T for Go1

calibrateIMUbiases: true #otherwise specify accurate initial values for bias_a, bias_g
maxImuCalibrationCycles: 100
#IMU Initial Biases in the IMU local frame - Biases are subtracted and are in the Body Frame!
bias_ax: 0.000
bias_ay: 0.000
bias_az: 0.000
bias_gx: 0.000
bias_gy: 0.000
bias_gz: 0.000

#Rigid body Extended Kalman Filter (EKF)
#To estimate:
# 3-D Body Position/Velocity
# 3-D IMU-Biases
contact_random_walk: 0.5
#Process Noise STDs
accelerometer_bias_random_walk:  2.4336e-04 #m/s^2/sqrt(s)
gyroscope_bias_random_walk: 1.0e-05 # rad/s/sqrt(s)
accelerometer_noise_density: 0.5 # m/s^2  #Continuous Time
gyroscope_noise_density: 0.05 # rad/s  #Continuous Time

leg_odom_position_noise_density: 5.0e-04
leg_odom_orientation_noise_density: 5.0e-02

#Measurements
odom_orientation_noise_density: 5.0e-02 #4
odom_position_noise_density_x: 3.5e-02 #2.0e-01
odom_position_noise_density_y: 3.5e-02
odom_position_noise_density_z: 1.0

velocity_noise_density_x: 0.035 #0.007
velocity_noise_density_y: 0.035 #0.009
velocity_noise_density_z: 0.035 #0.007
joint_noise_density: 0.2  # rad

#Filter Params
gravity: 9.80665 #gravity constant (m/s^2)

# CoM Extended Kalman Filter (EKF)
# To estimate:
# CoM 3-D Position/Velocity
# 3-D External Forces on the CoM
estimateCoM: true   #Use the CoM EKF

#---------------------------------------------#
#Specify the rest only if estimateCoM is true!!
#---------------------------------------------#

#Process Noise
com_position_random_walk: 1.0e-3 #in m
com_velocity_random_walk: 5.0e-1 #in m/s
external_force_random_walk: 5.0  #in Newtons
#Measurement Noise
com_position_noise_density: 1.0e-03    #CoM position in m
com_acceleration_noise_density: 1.9519 #CoM Acceleration in m/s^2
#Initial errors in External Forces
bias_fx: 0.0  #in Newtons
bias_fy: 0.0
bias_fz: 0.0
#Gyro LPF
useGyroLPF: false
#Cutt-off Frequencies
gyro_cut_off_freq: 10.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 5 #buffer size, the larger the smoother and delayed the signal,
# only if useGyroLPF is false
#Filter Params
Ixx : 0.038130318   #torso inertia around x
Iyy : 0.0089760596  #torso inetria around y
Izz : 0.039650845   #torso inertia around z
